# version: "3.1"

services:
  bagisto-php:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: bagisto-php-fpm
    volumes:
      - ./workspace:/var/www/html
    expose:
      - "80"
    networks:
      - bagisto-network

  bagisto-nginx:
    image: nginx:latest
    ports:
      - 8888:80
    volumes:
      - ./workspace:/var/www/html
      - ./.configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - bagisto-php
    networks:
      - bagisto-network

  bagisto-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bagisto
    ports:
      - 3306:3306
    volumes:
      - ./.configs/mysql-data:/var/lib/mysql/
    networks:
      - bagisto-network

  bagisto-redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./.configs/redis-data:/data
    networks:
      - bagisto-network

  bagisto-phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: bagisto-mysql
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 512M
    ports:
      - 8080:80
    networks:
      - bagisto-network

  bagisto-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./.configs/elasticsearch-data:/var/lib/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - bagisto-network

  bagisto-kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    environment:
      - ELASTICSEARCH_HOSTS=http://bagisto-elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - bagisto-elasticsearch
    networks:
      - bagisto-network

  bagisto-mailpit:
    image: axllent/mailpit:latest
    logging:
      driver: 'none'
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - bagisto-network

networks:
  bagisto-network:
    driver: bridge
